---
- name: Create Proxmox LXC Container from clone
  community.general.proxmox:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    clone: "{{ proxmox_object_clone_from_id }}"
    vmid: "{{ proxmox_object_id }}"
    hostname: "{{ proxmox_object_name }}"
    node: "{{ proxmox_primary_node }}"
    storage: "{{ proxmox_object_target_storage }}"

  when: proxmox_object_clone_from_id != -1

- name: Create Proxmox LXC Container from template
  community.general.proxmox:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    node: "{{ proxmox_primary_node }}"
    hostname: "{{ proxmox_object_name }}"
    password: "{{ proxmox_object_root_password }}"
    pubkey: "{{ lookup('file', proxmox_object_root_ssh_key) }}"
    ostemplate: "{{ proxmox_lxc_template_storage }}:vztmpl/{{ proxmox_lxc_template_name }}"
    disk: '{{ proxmox_object_root_disk_storage }}:{{ proxmox_object_root_disk_size }}'
    netif:
      net0: "name={{ proxmox_object_nic_name }},ip={{ proxmox_object_ipv4 }},ip6={{ proxmox_object_ipv6 }},bridge={{ proxmox_object_nic_bridge }},tag={{ proxmox_object_vlan }},firewall=1"
    state: present
    features:
      - nesting=1
    timeout: 300
  when: proxmox_lxc_template_name != ""