---
- name: Debug API Endpoint
  ansible.builtin.debug:
    msg: >
      "https://{{ proxmox_api_endpoint }}:8006/api2/json/nodes/{{ proxmox_primary_node }}/qemu/{{ proxmox_object_id }}/config"
  when: ansible_role_name in proxmox_debug or "all" in proxmox_debug

- name: Get VM configuration from Proxmox
  ansible.builtin.uri:
    url: "https://{{ proxmox_api_endpoint }}:8006/api2/json/nodes/{{ proxmox_primary_node }}/qemu/{{ proxmox_object_id }}/config"
    method: GET
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
  register: proxmox_vm_config

- name: Endpoint returned
  ansible.builtin.debug:
    msg: |-
      "{{ proxmox_vm_config.json.data | to_nice_json }}"
  when: ansible_role_name in proxmox_debug or "all" in proxmox_debug

- name: Extract MAC address of net0
  ansible.builtin.set_fact:
    proxmox_mac: >-
      {{
        (proxmox_vm_config.json.data.net0)
        | regex_findall('((?:[\da-fA-F]{2}[:\-]){5}[\da-fA-F]{2})', '\\1') | first
        | default('MAC address not found')
      }}
