---
- name: Restart VM
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    node: "{{ proxmox_primary_node }}"
    vmid: "{{ proxmox_object_id }}"
    state: "restarted"
  when: proxmox_object_status == "running"

- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    node: "{{ proxmox_primary_node }}"
    vmid: "{{ proxmox_object_id }}"
    state: "started"
  when: proxmox_object_status == "stopped"
