---
# This one works!
- name: Update VLAN on the Proxmox QEMU VM
  community.general.proxmox_nic:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    vmid: "{{ proxmox_object_id }}"
    bridge: "vmbr0"
    interface: net0
    tag: "{{ proxmox_object_vlan }}"
