---
- name: Create Proxmox LXC Container from clone
  community.general.proxmox:
    api_host: "{{ proxmox_api_endpoint }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    clone: "{{ proxmox_object_clone_from_id }}"
    vmid: "{{ proxmox_object_id }}"
    hostname: "{{ proxmox_object_name }}"
    node: "{{ proxmox_primary_node }}"
    storage: "{{ proxmox_object_target_storage }}"
